### PR TITLE
Split blog post partials

### PR DESCRIPTION
**Pull request by Sheco**
This PR splits the posts.htm file into posts.htm and post.htm, where post.html only shows a single post and posts.htm loops through the posts, including the post.htm partial.

It's just a minor patch.

The contents of post.htm is just exactly what posts.htm had.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Before and after screenshot please

**Comment by Sheco** [comment]
That's weird, I didn't notice this pull request's message was incorrect, that's silly, my apologies.

This pull request doesn't have a visible difference, it just splits the posts.htm file into posts.htm and post.htm, where post.html only shows a single post and posts.htm loops through the posts, including the post.htm partial.

It's just a minor patch.

The contents of post.htm is just exactly what posts.htm had.

**Comment by Sheco** [comment]
May I update this pull request's opening message?

**Comment by LukeTowers** [comment]
Gotcha. Feel free to edit whenever appropriate, GitHub shows the edit history.

**Comment by Sheco** [comment]
Thanks, you're the man!

**Pull request merged**
